# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regis_db',
            old_name='Emailid',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='regis_db',
            old_name='Name',
            new_name='name',
        ),
    ]
