# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore', '0002_auto_20180420_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=25)),
                ('Book_Name', models.CharField(max_length=25)),
                ('Author_Name', models.CharField(max_length=25)),
                ('Donater_name', models.CharField(max_length=25)),
                ('Mob_no', models.CharField(max_length=25)),
                ('Email_id', models.CharField(max_length=25)),
            ],
        ),
    ]
