# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore', '0003_donate_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=25)),
                ('Email_Address', models.CharField(max_length=25)),
                ('Mobile_No', models.CharField(max_length=25)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
