# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore', '0004_contact_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_db',
            name='filename',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
