# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore', '0005_donate_db_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_db',
            name='Book_Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='donate_db',
            name='Mob_no',
            field=models.IntegerField(max_length=25),
        ),
    ]
