# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 07:54
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore', '0006_auto_20180427_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_db',
            name='City_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donate_db',
            name='Select_State',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
